// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// calculate_sv_entropy
double calculate_sv_entropy(arma::mat A);
RcppExport SEXP _cytominer_calculate_sv_entropy(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_sv_entropy(A));
    return rcpp_result_gen;
END_RCPP
}
// CE_entropy_SR
NumericVector CE_entropy_SR(NumericMatrix A);
RcppExport SEXP _cytominer_CE_entropy_SR(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(CE_entropy_SR(A));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cytominer_calculate_sv_entropy", (DL_FUNC) &_cytominer_calculate_sv_entropy, 1},
    {"_cytominer_CE_entropy_SR", (DL_FUNC) &_cytominer_CE_entropy_SR, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_cytominer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
