// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// singular_value_entropy
double singular_value_entropy(arma::mat A);
RcppExport SEXP _cytominer_singular_value_entropy(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(singular_value_entropy(A));
    return rcpp_result_gen;
END_RCPP
}
// score_features_sv_entropy
NumericVector score_features_sv_entropy(NumericMatrix data);
RcppExport SEXP _cytominer_score_features_sv_entropy(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(score_features_sv_entropy(data));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cytominer_singular_value_entropy", (DL_FUNC) &_cytominer_singular_value_entropy, 1},
    {"_cytominer_score_features_sv_entropy", (DL_FUNC) &_cytominer_score_features_sv_entropy, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_cytominer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
