# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' calculate_entropy_new
#'
#' Calculate the entropy of a matrix singular values, when their summation is normalized to one.
#' @param A matrix of any arbitrary size
NULL

#' @return Calculate the entropy contribution of a matrix based on SVD
calculate_sv_entropy <- function(A) {
    .Call('_cytominer_calculate_sv_entropy', PACKAGE = 'cytominer', A)
}

#' CE_entropy_SR
#'
#' Calculate the entropy contribution of a matrix based on SVD
#' @param A dataset mxn (m features and n observations)
#' @return entropy contribution vector
CE_entropy_SR <- function(A) {
    .Call('_cytominer_CE_entropy_SR', PACKAGE = 'cytominer', A)
}

