# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' singular_value_entropy
#'
#' Calculate the entropy of a matrix singular values (SV) in the SVD decomposition, when the SVs summation is normalized to one.
#' @param A a matrix of any arbitrary size
#' @return entropy of the normalized singular values using log base 10
#'
#' @export
#'
singular_value_entropy <- function(A) {
    .Call('_cytominer_singular_value_entropy', PACKAGE = 'cytominer', A)
}

#' score_features_sv_entropy
#'
#' Scores each feature based on the difference of normalized SVs entropy of the data
#' with and without the feature; the higher the difference, the more informative the
#' feature would be.
#' @param data a matrix which represents the dataset; columns and rows correspond to features and observations, respectively.
#' @return vector containing scores for all the features, in the same order as the columns of data are arranged
#'
#' @export
#'
score_features_sv_entropy <- function(data) {
    .Call('_cytominer_score_features_sv_entropy', PACKAGE = 'cytominer', data)
}

