# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' calculate_entropy_new
#'
#' Calculate the entropy of a matrix based on SVD alternative method when more observations than features. A = XtX instead of A = Xt
#' @param A dataset mxm (m features and n observations)
NULL

#' @return Calculate the entropy contribution of a matrix based on SVD
calculate_entropy_new <- function(A) {
    .Call('_cytominer_calculate_entropy_new', PACKAGE = 'cytominer', A)
}

#' CE_entropy_SR
#'
#' Calculate the entropy contribution of a matrix based on SVD
#' @param A dataset mxn (m features and n observations)
#' @return entropy contribution vector
CE_entropy_SR <- function(A) {
    .Call('_cytominer_CE_entropy_SR', PACKAGE = 'cytominer', A)
}

#' CE_entropy_FS2_new
#'
#' Calculate the entropy of a matrix based on SVD with FS method
#' @param A dataset mxn (m features and n observations)
#' @param mc number of feature to select
#' @return index of features that were selected
CE_entropy_FS2_new <- function(A, mc) {
    .Call('_cytominer_CE_entropy_FS2_new', PACKAGE = 'cytominer', A, mc)
}

